services:
  _defaults:
    autowire: true
    autoconfigure: true

  Tourze\PayByPaymentBundle\Command\:
    resource: '../../Command/'
  Tourze\PayByPaymentBundle\Controller\:
    resource: '../../Controller/'
  Tourze\PayByPaymentBundle\Repository\:
    resource: '../../Repository/'
  Tourze\PayByPaymentBundle\Service\:
    resource: '../../Service/'
